import { Poppins, Gloock } from 'next/font/google'
import Header from './components/Header'

// Styles
import './globals.css'
import Footer from './components/Footer'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}
const poppins = Poppins({
  subsets: ['latin'],
  display: 'swap',
  weight: ['100', '300', '400', '600', '700', '900'],
  variable: '--font-poppins'
})

const gloock = Gloock({
  subsets: ['latin'],
  display: 'swap',
  weight: ['400'],
  variable: '--font-gloock'
})

export default function RootLayout({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={`${poppins.variable} ${gloock.variable}`}>
      <body>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  )
}
