import { Poppins, Cormorant_Garamond } from 'next/font/google'
import Header from './components/Header'

// Styles
import './globals.css'
import Footer from './components/Footer'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}
const poppins = Poppins({
  subsets: ['latin'],
  display: 'swap',
  weight: ['100', '300', '400', '600', '700', '900'],
  variable: '--font-poppins'
})

const cormorant_garamond = Cormorant_Garamond({
  subsets: ['latin'],
  display: 'swap',
  weight: ['300', '400', '500', '600', '700'],
  variable: '--font-cormorant-garamond'
})

export default function RootLayout({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html
      lang="en"
      className={`${poppins.variable} ${cormorant_garamond.variable}`}>
      <body>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  )
}
